### ISSUE TITLE
support for stack args

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell-stack#1]
such as building or testing with --pedantic

**Comment by lierdakil** [comment]
I'm not particularly familiar with stack, so I'd like to have a more or less complete list of command line arguments you'd need to pass, preferably with suggested use-cases.

For example, do you need to set `--pedantic` on a global, per-project or per-build basis?

**Comment by wolftune** [comment]
Various people will have different opinions. Some people will want to always use --pedantic and others never or manually. Basically, it's a matter of making the compiler stop if it has warnings rather than allow them. It's not a big deal, and the project I'm involved with the main devs prefer using --pedantic especially with testing before commits.

I'm not sure what other args people may or may not care about being able to set conveniently.

**Comment by lierdakil** [comment]
Okay, for the time being, I published v0.0.2 which allows to specify custom arguments in settings. It will probably prove to be clunky in the long run, but should be fine for now.
